### ISSUE TITLE
Add new textbook to the webpage

### ISSUE THREAD

**Issue by bsipocz** [astroML/astroml.github.com#11]
@ivezic - I think we should update the images and mentions of the textbook on the webpage, as well as maybe some new text. 

Do you have a preference for the timing? (e.g. only do after Dec 3, or now)? Any preference for new text?

**Comment by ivezic** [comment]
If you have time now, there is no need to wait for Dec 3. I think we can simply add the blurb about added new stuff, either from Preface, or from the PUP webpage.

**Comment by bsipocz** [comment]
Something bad happened with the PUP page, it used to work a week or two ago: https://press.princeton.edu/books/hardcover/9780691198309/statistics-data-mining-and-machine-learning-in-astronomy

**Comment by ivezic** [comment]
I'll wait until Dec 3 and then report to Ingrid if it doesn't come back on.
